COMPONENTS_IDS = {
    'alerts_section': 'alerts-section',
    'table_section': 'table-section',
    "app_interval": "app-interval",
    "bar_chart_button": "bar-chart-button",
    "bar_chart": "bar-chart",
    "charts_dropdowns": "charts-dropdowns",
    "control_buttons": "app-buttons",
    "control_section": "control-section",
    "date_picker_range": "date-picker-range",
    "first_dimension_dropdown": "first-dimension-dropdown",
    "hide_charts_button": "hide-charts-button",
    "info_cards": "info-cards",
    "pie_chart_button": "pie-chart-button",
    "restart_app_button_text": "restart-app-button-text",
    "restart_app_button": "restart-app-button",
    "second_dimension_dropdown": "second-dimension-dropdown",
    "show_charts_button": "show-charts-button",
    "show_database_button": "show-database-button",
    "start_app_button_spinner": "start-app-button-spinner",
    "start_app_button_text": "start-app-button-text",
    "start_app_button": "start-app-button",
    "status_section": "status-section",
}

STORE_IDS = {
    "done": "done",
    "error": "error",
    "first_dimension_label": "first_dimension_label",
    "first_dimension": "first_dimension",
    "loading": "loading",
    "second_dimension_label": "second_dimension_label",
    "second_dimension": "second_dimension",
    "success": "success",
}
